### ISSUE TITLE
JS Interop bug?

### ISSUE THREAD

**Issue by Rodsevich** [odroe/rc#1]
I included a dependency that depends on this package on a Flutter Web project using latest versions. This is the error when trying to compile afterwards:   
![image](https://user-images.githubusercontent.com/1907844/193440262-af8460cf-867a-47c0-aada-30cc7de92dcb.png)

**Comment by medz** [comment]
This is a bug

**Comment by medz** [comment]
Refactored `0.3.0` version, this issue has been resolved
